var map, entrance, boss, node1, node2;
map = global.roommap
entrance = ds_list_create()
boss = ds_list_create()
ds_list_add(entrance, 110447)
ds_list_add(entrance, 114131)
ds_list_add(entrance, 128081)
ds_list_add(entrance, 135439)
ds_list_add(entrance, 149904)
ds_list_add(boss, 110465)
ds_list_add(boss, 115276)
ds_list_add(boss, 127951)
ds_list_add(boss, 135483)
ds_list_add(boss, 149855)
fid = file_text_open_append("AreaRando/seed.txt")
while (ds_list_size(entrance) > 0)
{
    ds_list_shuffle(entrance)
    ds_list_shuffle(boss)
    node1 = ds_list_find_value(entrance, 0)
    node2 = ds_list_find_value(boss, 0)
    ds_list_delete(entrance, 0)
    ds_list_delete(boss, 0)
    file_text_write_string(fid, ((string(node1) + "-") + string(node2)))
    file_text_writeln(fid)
    ds_map_add(map, node1, node2)
    ds_map_add(map, node2, node1)
}
file_text_close(fid)
ds_list_destroy(boss)
ds_list_destroy(entrance)
